name: watchr

services:
  frontend:
    build:
      context: ./frontend
    image: watchr-frontend:0.1.0
    container_name: watchr-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: watchr-backend:0.1.0
    container_name: watchr-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: watchr-postgres
    environment:
      POSTGRES_USER: watchr
      POSTGRES_PASSWORD: watchr
      POSTGRES_DB: watchr
    ports:
      - "5432:5432"
    volumes:
      - watchr-postgres-data:/var/lib/postgresql/data

volumes:
  watchr-postgres-data:
